dependencies:
  factories:
    Zend\Expressive\Router\RouterInterface: Articus\PathHandler\Router\Factory\FastRouteAnnotation

Articus\PathHandler\Middleware:
  metadata_cache:
    adapter:
      name: blackhole
  handlers:
    abstract_factories:
      - Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory
#  consumers:
#    factories:
#    invokables:
#  attributes:
#    factories:
#    invokables:
#  producers:
#    factories:
#    invokables:

Articus\PathHandler\Router\FastRouteAnnotation:
  metadata_cache:
    adapter:
      name: blackhole
  handlers:
    - App\Handler\V4GeocodingReverse
    - App\Handler\V4GeocodingSearch
    - App\Handler\V4MapInfo
    - App\Handler\V4Routes
    - App\Handler\V4SupportedLocations
    - App\Handler\V4TimeFilter
    - App\Handler\V4TimeFilterFast
    - App\Handler\V4TimeFilterPostcodeDistricts
    - App\Handler\V4TimeFilterPostcodeSectors
    - App\Handler\V4TimeFilterPostcodes
    - App\Handler\V4TimeMap

Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory:
  App\Handler\V4GeocodingReverse: []
  App\Handler\V4GeocodingSearch: []
  App\Handler\V4MapInfo: []
  App\Handler\V4Routes: []
  App\Handler\V4SupportedLocations: []
  App\Handler\V4TimeFilter: []
  App\Handler\V4TimeFilterFast: []
  App\Handler\V4TimeFilterPostcodeDistricts: []
  App\Handler\V4TimeFilterPostcodeSectors: []
  App\Handler\V4TimeFilterPostcodes: []
  App\Handler\V4TimeMap: []
